### BASE URL in variable
@baseUrl = http://localhost:3000

### GET request to example server
# GET https://examples.http-client.intellij.net/get
#     ?generated-in=WebStorm

###

### POST request (login)
POST localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "kassidarius@gmail.com",
  "password": "Aazzeerrtt8888"
}

###
### GET request (meGet)
GET localhost:3000/api/auth/me

###